<?php
/**
 * WP Plastic Fields - Checkbox Field
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  WP Marvelous
 */

namespace WP_Marvelous\WP_Plastic_Fields\Field;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'WP_Marvelous\WP_Plastic_Fields\Field\Checkbox_Field' ) ) {

	class Checkbox_Field extends Field {

		public function get_default_values() {
			$default_values                              = parent::get_default_values();
			$default_values['sanitization']['default'][] = array( $this, 'sanitize_checkbox' );
			return $default_values;
		}

		public function get_field_output() {
			ob_start();
			?>
			<label for="<?php echo esc_attr( $this->id ); ?>">
				<input
					name="<?php echo esc_attr( $this->id ); ?>"
					id="<?php echo esc_attr( $this->id ); ?>"
					type="checkbox"
					class="<?php echo esc_attr( isset( $this->class ) ? $this->class : '' ); ?>"
					value="1"
					<?php checked( $this->get_value(), 'yes' ); ?>
					<?php echo implode( ' ', $this->get_custom_attributes() ); // WPCS: XSS ok. ?>
				/> <?php echo $this->get_field_description()['description']; // WPCS: XSS ok. ?>
			</label> <?php echo $this->get_field_description()['tooltip_html']; // WPCS: XSS ok. ?>
			<?php
			return ob_get_clean();
			//return parent::get_field_output(); // TODO: Change the autogenerated stub
		}
	}
}