<?php
/**
 * WP Plastic Fields -Title Field
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  WP Marvelous
 */

namespace WP_Marvelous\WP_Plastic_Fields\Field;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'WP_Marvelous\WP_Plastic_Fields\Field\Title_Field' ) ) {

	class Title_Field extends Field {
		public function get_default_values() {
			$default_values                  = parent::get_default_values();
			$default_values['display_style'] = 'one_column';
			return $default_values;
		}

		public function get_presentation_output() {
			ob_start();
			?>
			<?php //do_action( "plf_container_{$this->container->id}_field_{$this->id}_icons", $this ); ?>
			<h2><?php echo wp_kses_post( $this->title ); ?></h2>
			<?php
			return ob_get_clean();
		}

		public function get_field_output() {
			ob_start();
			?>
			<div id="<?php echo esc_attr( $this->id ); ?>-description">
				<p><?php echo $this->desc; ?></p>
			</div>
			<?php
			return ob_get_clean();
			//return parent::get_field_output(); // TODO: Change the autogenerated stub
		}
	}
}