<?php
/**
 * WP Plastic Fields - Woo Options Page Container
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  WP Marvelous
 */

namespace WP_Marvelous\WP_Plastic_Fields\Container;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'WP_Marvelous\WP_Plastic_Fields\Container\Woo_Options_Page_Container' ) ) {
	class Woo_Options_Page_Container extends Container {
		public function init() {
			add_filter( 'woocommerce_settings_tabs_array', array( $this, 'create_wc_settings_tab' ), 40 );
			add_filter( "plf_container_{$this->id}_navigation", array( $this, 'override_navigation_params' ) );

			//add_action( 'woocommerce_settings_tabs', array( $this, 'init_container_navigation' ), 11 );
			//add_action( 'woocommerce_settings_tabs', array( $this, 'display_container_navigation' ), 12 );

			// Menu
			/*add_action( 'admin_menu', array( $this, 'handle_admin_menus' ) );

			//add_action( 'plf_container_' . 'plastic_slug' . '_navigation', function ( Container $container ) {

			// Before Container
			add_action( 'plf_before_container', array( $this, 'display_container_title' ), 10 );
			add_action( 'plf_before_container', array( $this, 'init_container_navigation' ), 11 );
			add_action( 'plf_before_container', array( $this, 'display_container_navigation' ), 12 );

			// Container
			add_action( 'plf_container', array( $this, 'init_fields_groups' ), 12 );
			add_action( 'plf_container', array( $this, 'detect_submit_btn' ), 13 );
			add_action( 'plf_container', array( $this, 'display_container_messages' ), 14 );

			// Container Form
			add_action( 'plf_container_form', array( $this, 'display_fields_groups' ), 12 );
			add_action( 'plf_container_form', array( $this, 'display_container_form_actions' ), 15 );

			// Show success message
			add_action( "plf_container_{$this->id}_submit", array( $this, 'check_validation_errors_after_submit' ), 20 );
			add_action( "plf_container_{$this->id}_no_validation_errors_after_submit", array( $this, 'show_success_message_after_submit' ) );*/

			//parent::init(); // TODO: Change the autogenerated stub
		}

		public function override_navigation_params( $params ) {
			$params                                 = parent::override_navigation_params( $params );
			$params['original_url']                 = admin_url( 'admin.php?page=wc-settings' );
			$params['query_string']['level_params'] = array( 'tab' );
			$params['query_string']['level_prefix'] = 'lvl_';
			$params['hide_levels']                  = array( 0 );
			return $params;
		}

		/*function override_navigation_params( $params ) {
			$params['original_url']                 = admin_url( 'admin.php?page=wc-settings' );
			$params['query_string']['level_params'] = array( 'tab' );
			$params['query_string']['level_prefix'] = 'lvl_';
			$params['hide_levels']                  = array( 0 );
			return $params;
		}*/

		/*function init_container_navigation() {
			do_action( "plf_container_{$this->id}_set_navigation", $this );
			if ( empty( $this->navigation ) ) {
				return;
			}

			$this->navigation->init();
		}*/

		function create_wc_settings_tab( $settings_tabs ) {
			do_action( "plf_container_{$this->id}_set_navigation", $this );
			if ( empty( $this->navigation ) ) {
				return;
			}
			$new_tab_id = '';
			foreach ( $this->navigation->args['levels'] as $arg ) {
				if ( 0 == $arg['level'] ) {
					$id                   = $new_tab_id = $arg['items'][0]['id'];
					$title                = $arg['items'][0]['title'];
					$settings_tabs[ $id ] = $title;
					break;
				}
			}
			add_action( 'woocommerce_sections_' . $new_tab_id, array( $this, 'init_container_navigation' ), 11 );
			add_action( 'woocommerce_sections_' . $new_tab_id, array( $this, 'display_container_navigation' ), 12 );

			add_action( 'woocommerce_settings_' . $new_tab_id, array( $this, 'init_fields_groups' ), 11 );
			//add_action( 'woocommerce_sections_' . $new_tab_id, array( $this, 'detect_submit_btn' ), 13 );
			//add_action( 'woocommerce_sections_' . $new_tab_id, array( $this, 'display_container_messages' ), 14 );

			// Container Form
			add_action( 'woocommerce_settings_' . $new_tab_id, array( $this, 'display_fields_groups' ), 12 );
			//add_action( 'woocommerce_sections_' . $new_tab_id, array( $this, 'display_container_form_actions' ), 15 );

			// Show success message
			//add_action( "plf_container_{$this->id}_submit", array( $this, 'check_validation_errors_after_submit' ), 20 );
			//add_action( "plf_container_{$this->id}_no_validation_errors_after_submit", array( $this, 'show_success_message_after_submit' ) );*/




			return $settings_tabs;
		}
	}
}